name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.make.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        rust: [ stable ]
        # List of feature builds to test
        features: [ --all-features, --no-default-features ]
    env:
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build ${{ matrix.features }} --verbose
    - name: Clippy
      run: cargo clippy ${{ matrix.features }} --verbose
