name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust, feature=${{ matrix.features }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        rust: [ stable ]
        # List of feature builds to test
        features: [ --all-features, --no-default-features ]
        include:
          - os: ubuntu-latest
            cargo-dir-path: /home/runner/.cargo/
            cache-dir: /home/runner/
    env:
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ${{ matrix.cache-dir-path }}bin
          ${{ matrix.cache-dir-path }}registry/index/
          ${{ matrix.cache-dir-path }}registry/cache/
          ${{ matrix.cache-dir-path }}git/db/
        key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build ${{ matrix.features }} --verbose
    - name: Clippy
      run: cargo clippy ${{ matrix.features }} --verbose
